name: generate-snake

on:
  schedule:
    - cron: "0 0 * * *"  # se ejecuta todos los días a medianoche UTC
  workflow_dispatch:      # permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: anthonyreynaDev
          outputs: dist/github-contribution-grid-snake.svg
          color_snake: "#BD93F9" # color de la serpiente (violeta brillante)
          color_dots: "#282A36,#44475A,#6272A4,#8BE9FD,#FF79C6" # colores de los cuadritos (Dracula)

      - name: Push snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
